[project]
name = "panqake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prompt-toolkit>=3.0.51",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
